---
# tasks file for __template__
- name: Copy a file
  copy: src=test.tar dest=/home/{{ user_name }}/test.tar
- name: Install common software requirements
  apt: pkg={{ item }} state=installed
  with_items:
   - git
   - htop
   - vim
   - curl
   - sudo
   - zsh

- name: Create the sudo group
  group:
   name=sudo
   state=present

#- name: Create a new user
#  user:
#   name={{ user_name }}
#  state=present
#  groups="sudo"
#  shell=/bin/zsh
#  password=$6$DDYFfY5.$E8.FbXHdRHsJiNBNkQsFLY8AkUriPT4naXMwQoo8XK3yG/5TL0hxSXmEgTygU.BdghC7FoDcAY2BMncikjtii.

- name: Create home directory folder structure
  file: path=/home/{{ user_name }}/{{ item }}
   state=directory
   owner={{ user_name }}
   group={{ user_name }}
   mode=0700
  with_items:
   - src
   - backups
   - bin
   - subdir

- name: Copy multiple files 
  copy: src={{ item }} dest=/home/{{ user_name }}/{{ item }}
   owner={{ user_name }}
   group={{ user_name }}
   mode=0755
  with_items:
   - test.tar
   - first.bin
   - subdir/second.bin
